### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by mahdi7** [madeleineudell/SigmoidalProgramming.jl#1]
I keep getting this error both on Windows and Linux:

julia> Pkg.clone("git@github.com:madeleineudell/SigmoidalProgramming.jl.git")
INFO: Cloning SigmoidalProgramming from git@github.com:madeleineudell/SigmoidalProgramming.jl.git
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
ERROR: unlink: no such file or directory (ENOENT)
 in unlink at fs.jl:97
 in rm at file.jl:57
 in clone at pkg/entry.jl:151
 in clone at pkg/entry.jl:175
 in anonymous at pkg/dir.jl:28
 in cd at ./file.jl:20
 in **cd#228** at ./pkg/dir.jl:28
 in clone at pkg.jl:30

**Comment by madeleineudell** [comment]
i believe this error occurs because you haven't uploaded an ssh public key
to github. does it work if you use the http clone url instead:

https://github.com/madeleineudell/SigmoidalProgramming.jl.git

?

On Wed, Mar 11, 2015 at 3:35 PM, mahdi7 notifications@github.com wrote:

> I keep getting this error both on Windows and Linux:
> 
> julia> Pkg.clone("git@github.com
> :madeleineudell/SigmoidalProgramming.jl.git")
> INFO: Cloning SigmoidalProgramming from git@github.com
> :madeleineudell/SigmoidalProgramming.jl.git
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> ERROR: unlink: no such file or directory (ENOENT)
> in unlink at fs.jl:97
> in rm at file.jl:57
> in clone at pkg/entry.jl:151
> in clone at pkg/entry.jl:175
> in anonymous at pkg/dir.jl:28
> in cd at ./file.jl:20
> in _cd#228_ at ./pkg/dir.jl:28
> in clone at pkg.jl:30
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/madeleineudell/SigmoidalProgramming.jl/issues/1.

## 

Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by mahdi7** [comment]
Thank you Madeleine. 
I uploaded an SSH public key and that resolved the problem.

**Comment by RoyiAvital** [comment]
@madeleineudell ,
You should update the PDF links on README.md.
Best to put them as part of package so the link will be constant for good.
